version: "3.8"
services:
  mariadb:
    volumes:
      - mariadb_run:/var/run/mysqld
      - ./data/mariadb_data:/var/lib/mysql

  git:
    ports:
      - "22:2222"
    volumes:
      - ./data/git_data:/aurweb/aur.git
      - ./data:/aurweb/data
      - ./keys/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - ./keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro

  smartgit:
    volumes:
      - ./data/git_data:/aurweb/aur.git
      - ./data:/data
      - smartgit_run:/var/run/smartgit
